version: "3"

services:
  server:
    build: "./backend"
    expose:
      - ${BACKEND_PORT}
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ./backend/src:/srv/app/backend/src
