export const START_MOVIE_FETCHING = "START_MOVIE_FETCHING";
export const SUCCESS_MOVIE_FETCHING = "SUCCESS_MOVIE_FETCHING";
export const FAILED_MOVIE_FETCHING = "FAILED_MOVIE_FETCHING";

export const SEARCHING_MOVIE = "SEARCHING_MOVIE";
