export const START_MOVIE_FETCHING = "START_MOVIE_FETCHING";
export const SUCCESS_MOVIE_FETCHING = "SUCCESS_MOVIE_FETCHING";
export const ERROR_MOVIE_FETCHING = "ERROR_MOVIE_FETCHING";
export const FAILED_MOVIE_FETCHING = "FAILED_MOVIE_FETCHING";
export const CONTINUE_MOVIE_FETCHING = "CONTINUE_MOVIE_FETCHING";

export const START_MOVIE_DETAIL_FETCHING = "START_MOVIE_DETAIL_FETCHING";
export const SUCCESS_MOVIE_DETAIL_FETCHING = "SUCCESS_MOVIE_DETAIL_FETCHING";
export const FAILED_MOVIE_DETAIL_FETCHING = "FAILED_MOVIE_DETAIL_FETCHING";

export const SEARCHING_MOVIE = "SEARCHING_MOVIE";
export const UPDATE_SEARCH_DATA = "UPDATE_SEARCH_DATA";
